### ISSUE TITLE
Single-clicking a cell should visually indicate its state

### ISSUE THREAD

**Issue by emarc** [vaadin/vaadin-grid-pro#77] opened 2019-03-14 17:23 UTC
Single-clicking an editable cell clearly activates it (focus?) behind the scenes, but it's not visually indicated in any way. Pressing enter (or typing if it's text) triggers editmode for the cell you just clicked. 

Indicating this state would be great for usability;  the user would more easily discover how to interact with the component, and mistakes avoided (typing in the wrong cell).

Reproduce: 
1. Click cell -> nothing happens
2. Press enter -> editmode
3. Press enter -> this is how it should have looked in step 1

https://d.pr/v/Pw6aV8

**Comment by web-padawan** [comment] 2019-03-14 19:20
Duplicate of #61 and the fix has been released in 1.0.1
Looks like [website demo](https://vaadin.com/components/vaadin-grid-pro/html-examples/grid-pro-edit-column-demos) is not yet updated to use Vaadin 13.0.1 where it is included.

**Closed by web-padawan** 2019-03-14 19:20 UTC
